### ISSUE TITLE
Npc not spawn [BUG]

### ISSUE THREAD

**Issue by PeppoDevStudio** [jfoucher/simplest-bukkit-gps#1]
Hi i have this bug:

![image](https://github.com/jfoucher/simplest-bukkit-gps/assets/70705179/30a3ba55-baa7-4607-a667-6f42c7cf1f31)

**Comment by PeppoDevStudio** [comment]
![image](https://github.com/jfoucher/simplest-bukkit-gps/assets/70705179/1131041f-d732-4a65-9856-bbc06b0b492a)

Also could you add the functionality of a trail to take you to your destination?

**Comment by jfoucher** [comment]
Very strange bug, since the line just before says `npc spawned true`

What is the distance between the start and end point more or less ?

**Comment by PeppoDevStudio** [comment]
100/150 blocks

**Comment by PeppoDevStudio** [comment]
I use 1.20.4

**Comment by jfoucher** [comment]
Can you turn your logging to the FINEST level and copy/paste the log here ?

**Comment by PeppoDevStudio** [comment]
in what sense?

**Comment by PeppoDevStudio** [comment]
![image](https://github.com/jfoucher/simplest-bukkit-gps/assets/70705179/717f0764-67e3-4a3b-a223-f419afb27cb3)

**Comment by PeppoDevStudio** [comment]
The NPC appears and disappears..

**Comment by jfoucher** [comment]
Start the server like this : `java -Dpaper.log-level=FINEST -jar paper.jar` 
I'm not sure how to do it with pufferfish though, their doc probably mentions it somewhere.

**Comment by PeppoDevStudio** [comment]
And for death bug?

**Comment by jfoucher** [comment]
Sorry, what is the death bug? If there is another bug, please open another issue. If you want me to solve this one though, please give me the log file as requested above. Paste it as text and not as a screenshot. Thanks

**Comment by PeppoDevStudio** [comment]
Not work, i have this bug:

https://mclo.gs/nGLVET7

**Comment by PeppoDevStudio** [comment]
Npc spawn and disappeared

**Comment by PeppoDevStudio** [comment]
Always appear this:

[16:10:49 WARN]: [GPS] player finder is NULL
[16:10:49 INFO]: [GPS] zPeppo_ set GPS to Test1
[16:10:49 INFO]: [GPS] npc spawned true

**Comment by jfoucher** [comment]
Please provide a detailed log on the FINEST log level. Try the plugin with [PaperMC 1.20.4](https://papermc.io/downloads) and run the server like this : `java -Dpaper.log-level=FINEST -jar paper-1.20.4.jar`

I WILL NOT be able to solve this issue unless you provide a log at the FINEST level, so please stop spamming this issue until you do.

**Comment by PeppoDevStudio** [comment]
I don't want to use Paper, you should try Pupperfish and solve the problem...

**Comment by jfoucher** [comment]
It works perfectly for me on pufferfish

**Comment by PeppoDevStudio** [comment]
I use 1.20.4, you?

**Comment by jfoucher** [comment]
Yes, the latest version from pufferfish website. Build #46

**Comment by jfoucher** [comment]
Did you manage to solve it?
